---
- debug:
    msg: "nginx user: {{ nginx_user }}"

- name: check if EPEL repo is already configured.
  stat: path="/etc/yum.repos.d/epel.repo"
  register: epel_repofile_result
 
- name: install EPEL repo.
  yum:
    name: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm"
    state: present
  register: result
  when: not epel_repofile_result.stat.exists
 
- name: import EPEL GPG key.
  rpm_key:
    key: "https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-{{ ansible_distribution_major_version }}"
    state: present
  when: not epel_repofile_result.stat.exists

- name: install nginx
  package:
    name: nginx 
    state: latest

- name: ensure nginx user group exists
  group:
    name: "{{ nginx_user }}"
    state: present

- name: ensure nginx user exists
  user: 
    name: "{{ nginx_user }}" 
    comment: "nginx web user" 
    shell: "/usr/bin/false" 
    groups: "{{ nginx_user }}" 
    home: "{{ webroot }}"
 
- name: set correct www directory ownership
  file:
    state: directory
    path: "{{ webroot }}"
    owner: "{{ nginx_user }}"
    group: "{{ nginx_user }}"
    recurse: yes

- name: update nginx.conf
  template:
    src: "nginx.conf.j2" 
    dest: "/etc/nginx/nginx.conf" 

- name: "add the site config"
  template:
    src: virtualhost.conf.j2
    dest: "/etc/nginx/conf.d/default.conf"
    owner: root
    group: root