---
- name: install nginx
  package:
    name: nginx 
    state: latest

- name: ensure nginx user group exists
  group:
    name: "${var.nginx_user}"
    state: present

- name: ensure nginx user exists
  user: 
    name: "${var.nginx_user}" 
    comment: "nginx web user" 
    shell: "/usr/bin/false" 
    groups: "${var.nginx_user}" 
    home: "${var.webroot}"
 
- name: set correct www directory ownership
  file:
    state: directory
    path: "{var.webroot}"
    owner: "${var.nginx_user}"
    group: "${var.nginx_user}"
    recurse: yes

- name: update nginx.conf
  template:
    src: "nginx.conf.j2" 
    dest: "/etc/nginx/nginx.conf" 

- name: "add the site config"
  template:
    src: virtualhost.conf.j2
    dest: "/etc/nginx/conf.d/default.conf"
    owner: root
    group: root